sudo: required

language: generic

branches:
  only:
    - main

service:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t mizeloble/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true mizeloble/docker-react-app npm run test -- --coverage

  after_success:
    - echo "Test Success"

